on:
    pull_request:
        types: [opened, synchronize, reopened]
        branches:
            - master
        paths:
            - 'force-app/**'
jobs:
    validate-branch-name:
        runs-on: ubuntu-latest
        steps:
            - name: Validate branch name requirements
              uses: Shubhrajitdey/sfdc-ci-cd-org-dev@master
              with:
                  regex: '([a-z])+\/([a-z])+'
                  min_length: 6